tests/vboot: Fix mocked function list
This change fixes the following build failure when running unit tests:
```
$ make tests/vboot/secdata_tpm-test
    CC       tests/vboot/secdata_tpm-test/run
(...)libpayload.a(tlcl.o): in function `TlclExtend':
tlcl.c:(...): multiple definition of `TlclExtend'; (...)
(...)/libpayload.a(tlcl.o): in function `TlclLockPhysicalPresence':
tlcl.c:(...): multiple definition of `TlclLockPhysicalPresence'; (...)
collect2: error: ld returned 1 exit status
make: *** [tests/Makefile.inc:51: (...)/vboot/secdata_tpm-test/run] Error 1
```

BUG=b:449097147
BRANCH=main
TEST=make tests/vboot/secdata_tpm-test

Change-Id: I1834fbcceb1bd840a4d620c384d5e2661830c8ce
Signed-off-by: Bartłomiej Grzesik <bgrzesik@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/7044689
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Reviewed-by: Julius Werner <jwerner@chromium.org>
Reviewed-by: Grzegorz Bernacki <bernacki@google.com>
(cherry picked from commit 08dd1e7bd0bab18ced6eeebdd8d9496f9660e5db)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/7105861
Reviewed-by: Konrad Adamczyk <konrada@google.com>
Tested-by: Grzegorz Bernacki <bernacki@google.com>
Commit-Queue: Grzegorz Bernacki <bernacki@google.com>