drivers/sound/hda_codec: Fix int-to-pointer-cast error
The fatcat build is failing due to the following error:
src/drivers/sound/hda_codec.c:173:11: error: cast to pointer from integer of
different size [-Werror=int-to-pointer-cast]
  173 |    return (void *)(pci_read_resource(hda_dev, 0) & ~0xf);
      |           ^

BUG=none
TEST=cq
BRANCH=none

Change-Id: I7485037a371e289c73d1957f2ecde3b927dacaf4
Signed-off-by: Ian Feng <ian_feng@compal.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6022386
Reviewed-by: Subrata Banik <subratabanik@chromium.org>
Commit-Queue: Subrata Banik <subratabanik@chromium.org>
(cherry picked from commit 5c91cd9082f114393f17d15d3dfcd24473eff961)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/7202183
Tested-by: Tony Huang <tony-huang@quanta.corp-partner.google.com>
Reviewed-by: Oscar Liu <oscarliu@google.com>
Reviewed-by: Derek Huang <derekhuang@google.com>
Commit-Queue: Tony Huang <tony-huang@quanta.corp-partner.google.com>