arch/x86/boot: Fix int-to-pointer-cast error
The fatcat build is failing due to the following error:

 src/arch/x86/boot.c:107:29: error: cast to pointer from integer of
 different size [-Werror=int-to-pointer-cast]
 107 |      fixup_android_boottime((void *)hdr->ramdisk_image, hdr->ramdisk_size,
     |                             ^

I'm not sure why brya and dedede are not having the same error reported,
but the problem should be fixed by first casting the integer to
uintptr_t.

BUG=none
TEST=cq
BRANCH=none

Change-Id: I62e2d1cd5e60189f0c1940e80a3bf686a1a5f4d2
Signed-off-by: Yu-Ping Wu <yupingso@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/5922583
Commit-Queue: Jonathon Murphy <jpmurphy@google.com>
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>
(cherry picked from commit c8068176f8e5552d5beaed200dae7e6e900512f9)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/6557323
Commit-Queue: Yidi Lin <yidilin@google.com>
Tested-by: Yidi Lin <yidilin@google.com>